//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by vfeat.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_VFEATTYPE                   129
#define VA_ID_ANALYSE                   32771
#define ID_MENUITEM32772                32772
#define VM_ID_LINE                      32774
#define VM_ID_RECTANGLE                 32775
#define VM_ID_ELLIPSE                   32776
#define VM_ID_TEXT                      32778
#define VM_ID_POLYLINE                  32779
#define ID_MENUITEM32781                32781
#define VM_ID_FREEHAND                  32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
